[{"name": "test.test_bank.BankTest.test_bank", "status": "errored", "message": "NOT NULL constraint failed: pages_account.owner_id", "passed": false, "points": ["2.6.1", "2.6.2", "2.6.3", "2.6.4", "2.6.5"], "backtrace": ["  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/Users/hamidebadi/Desktop/cyber_security_2020/mooc-securing-software-20/part2-12.simplebanking/test/test_bank.py\", line 33, in test_bank\n    response = self.client.post('/add/', {'iban': iban1}, follow=True)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/test/client.py\", line 742, in post\n    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/test/client.py\", line 404, in post\n    return self.generic('POST', path, post_data, content_type,\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/test/client.py\", line 470, in generic\n    return self.request(**r)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/test/client.py\", line 710, in request\n    self.check_exception(response)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/test/client.py\", line 571, in check_exception\n    raise exc_value\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n    response = get_response(request)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py\", line 179, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/contrib/auth/decorators.py\", line 21, in _wrapped_view\n    return view_func(request, *args, **kwargs)\n", "  File \"/Users/hamidebadi/Desktop/cyber_security_2020/mooc-securing-software-20/part2-12.simplebanking/src/pages/views.py\", line 15, in addView\n    Account.objects.create(owner = user, iban = iban_num)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py\", line 447, in create\n    obj.save(force_insert=True, using=self.db)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/base.py\", line 753, in save\n    self.save_base(using=using, force_insert=force_insert,\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/base.py\", line 790, in save_base\n    updated = self._save_table(\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/base.py\", line 895, in _save_table\n    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/base.py\", line 933, in _do_insert\n    return manager._insert(\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py\", line 1254, in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/compiler.py\", line 1397, in execute_sql\n    cursor.execute(sql, params)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py\", line 66, in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py\", line 75, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py\", line 84, in _execute\n    return self.cursor.execute(sql, params)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/utils.py\", line 90, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py\", line 84, in _execute\n    return self.cursor.execute(sql, params)\n", "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py\", line 413, in execute\n    return Database.Cursor.execute(self, query, params)\n"]}]